# Generated by Django 4.2.1 on 2023-06-03 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0003_members_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co_signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('from_city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('potential_client', models.BooleanField()),
            ],
            options={
                'verbose_name': 'co_signer',
                'verbose_name_plural': 'co_signers',
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stipulated_time', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Modality',
                'verbose_name_plural': 'Modalitys',
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota_mensual', models.IntegerField()),
                ('plazo_meses', models.IntegerField()),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.members')),
                ('Modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.modality')),
                ('co_signer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.co_signer')),
            ],
        ),
    ]
