# Generated by Django 4.2.1 on 2023-06-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_loans_options_alter_loans_co_signer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modality',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
