# Generated by Django 4.2.1 on 2023-06-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_modality_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='cuota_mensual',
            new_name='monthly_fee',
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='plazo_meses',
            new_name='term_months',
        ),
    ]
