# Generated by Django 4.2.1 on 2023-06-02 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyes',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 6, 2, 14, 20, 46, 199857, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
