# Generated by Django 4.2.1 on 2023-06-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_members_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co_signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('from_city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('potential_client', models.BooleanField()),
            ],
            options={
                'verbose_name': 'co_signer',
                'verbose_name_plural': 'co_signers',
            },
        ),
        migrations.AddField(
            model_name='members',
            name='co_signer',
            field=models.ManyToManyField(to='socios.co_signer'),
        ),
    ]
