# Generated by Django 4.2.1 on 2023-06-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_rename_co_signer_members_co_signers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='co_signers',
        ),
        migrations.AddField(
            model_name='co_signer',
            name='member',
            field=models.ManyToManyField(to='socios.members'),
        ),
    ]
