# Generated by Django 4.2.1 on 2023-06-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_remove_members_co_signers_co_signer_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co_signer',
            name='member',
        ),
        migrations.AddField(
            model_name='members',
            name='co_signers',
            field=models.ManyToManyField(to='socios.co_signer'),
        ),
    ]
