# Generated by Django 4.2.1 on 2023-06-01 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 6, 1, 21, 56, 40, 77578, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
